# Generated by Django 3.1 on 2022-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgestatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgestatus',
            name='problemID',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='judgestatus',
            name='verdict',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
