# Generated by Django 3.1 on 2022-04-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='bank',
            new_name='problemlists',
        ),
    ]
