# Generated by Django 2.2 on 2022-03-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemID', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('problem_background', models.TextField()),
                ('problem_description', models.TextField()),
                ('problem_input', models.TextField()),
                ('problem_output', models.TextField()),
                ('problem_note', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('problem_difficulty', models.IntegerField()),
                ('problem_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_example', models.TextField()),
                ('output_example', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem')),
            ],
        ),
    ]
