# Generated by Django 3.1 on 2022-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemID', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('problem_background', models.TextField()),
                ('problem_description', models.TextField()),
                ('problem_input', models.TextField()),
                ('problem_output', models.TextField()),
                ('example_list', models.TextField()),
                ('problem_note', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('problem_difficulty', models.IntegerField()),
                ('problem_source', models.CharField(max_length=100)),
            ],
        ),
    ]
