# Generated by Django 3.1 on 2022-04-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemlist',
            old_name='listID',
            new_name='listName',
        ),
    ]
